name: pact-test-and-release

on:
  push:
  pull_request:
    types:
      - closed

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACTICIPANT: MartinsMessageConsumer
  PACTICIPANT_VERSION: ${{ github.sha }}

jobs:
  test:
    if: ${{ github.event.pull_request.state != 'closed'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test --ci
      - name: Publish contract
        run: >
          yarn pact-broker publish pacts 
          --broker-base-url $PACT_BROKER_BASE_URL 
          --broker-token $PACT_BROKER_TOKEN 
          --consumer-app-version $PACTICIPANT_VERSION 
          --tag ${{ github.ref }}   

  can-i-deploy:
    if: ${{ github.ref != 'refs/heads/master' }}
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - uses: ./.github/actions/can-i-deploy
        with:
          stage: dev
          version: ${{ github.sha }}
          pacticipant: $PACTICIPANT

  dev:
    needs: test
    if: ${{ github.ref == 'refs/heads/master' }}
    name: Deploy to dev
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - uses: ./.github/actions/release
        with:
          stage: dev
          version: ${{ github.sha }}
          pacticipant: $PACTICIPANT 

  staging:
    needs: dev
    name: Deploy to staging
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - uses: ./.github/actions/release
        with:
          stage: staging
          version: ${{ github.sha }}
          pacticipant: $PACTICIPANT 

  production:
    needs: staging
    name: Deploy to production
    environment:
      name: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - uses: ./.github/actions/release
        with:
          stage: production
          version: ${{ github.sha }}
          pacticipant: $PACTICIPANT 
