name: pact-test

on:
  pull_request:
    types: [opened, synchronize]

env:
  PACT_BROKER_BASE_URL: ${{secrets.PACT_BROKER_BASE_URL}}
  PACT_BROKER_TOKEN: ${{secrets.PACT_BROKER_TOKEN}}
  PACTICIPANT: MartinsMessageConsumer
  PACTICIPANT_VERSION: ${{ github.event.pull_request.head.sha }}
  DEPLOY_TARGET: ${{ github.base_ref }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
      - name: Publish contract
        run: >
          yarn pact-broker publish pacts 
          --broker-base-url $PACT_BROKER_BASE_URL 
          --broker-token $PACT_BROKER_TOKEN 
          --consumer-app-version $PACTICIPANT_VERSION 
          --tag $GITHUB_HEAD_REF
      - name: Can i deploy?
        run: >
          yarn pact-broker can-i-deploy
          --pacticipant $PACTICIPANT
          --version $PACTICIPANT_VERSION
          --to $DEPLOY_TARGET
          --retry-while-unknown 3 
          --retry-interval 30
          --broker-base-url $PACT_BROKER_BASE_URL
          --broker-token $PACT_BROKER_TOKEN



